spring:
  application:
    name: orchestration-service
  datasource:
    url: jdbc:postgresql://localhost:5432/eventuate
    username: eventuate
    password: eventuate
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eventuate:
  kafka:
    bootstrap:
      servers: localhost:9092
  database:
    schema: eventuate

server:
  port: 8084

logging:
  level:
    io.eventuate: DEBUG
    io.realguardio: DEBUG